version: "3.8"
services:
  mqtt2prometheus:
    image: hikhvar/mqtt2prometheus:v0.1.5
    command:
      - /mqtt2prometheus
      - -log-level
      - debug
      - -config
      - /config.yaml
    ports:
      - 9641:9641
    volumes:
      - type: bind
        source: ./${CONFIG:-configuration.yaml}
        target: /config.yaml
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
    - 1883:1883
    - 9001:9001
  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
    - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
  loudml:
    image: loudml/loudml:latest
    container_name: loudml
    ports:
        - "8077:8077"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=yourmail@gmail.com
      - GF_SMTP_PASSWORD=<your_password>
      - GF_SMTP_FROM_ADDRESS=yourmail@gmail.com
      - GF_INSTALL_PLUGINS= grafana-worldmap-panel,https://github.com/vsergeyev/loudml-grafana-app/raw/master/grafana-loudml-app-1.1.0.zip;grafana-loudml-app
    user: "104"